# Generated by Django 5.2.17 on 2026-08-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="book",
            constraint=models.UniqueConstraint(
                fields=("title", "author", "cover"),
                name="unique_book_title_author_cover",
            ),
        ),
    ]
