# Generated by Django 5.2.17 on 2026-08-27 09:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_book_unique_book_title_author_cover"),
        ("borrowings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="borrowing",
            name="check_expected_return_date_after_borrow_date",
        ),
        migrations.AddConstraint(
            model_name="borrowing",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("expected_return_date__gt", models.F("borrow_date"))
                ),
                name="check_expected_return_date_after_borrow_date",
            ),
        ),
    ]
